import credentials
import os
import google.generativeai as genai
from gtts import gTTS
import pygame
import speech_recognition as sr
import re
import RPi.GPIO as GPIO
import time

# Servo motor setup
SERVO_PIN = 17  # Adjust based on your servo setup
GPIO.setmode(GPIO.BCM)
GPIO.setup(SERVO_PIN, GPIO.OUT)
pwm = GPIO.PWM(SERVO_PIN, 50)  # Set PWM frequency to 50Hz
pwm.start(0)

# Function to rotate servo
def rotate_servo(angle):
    duty_cycle = 2 + (angle / 18)
    GPIO.output(SERVO_PIN, True)
    pwm.ChangeDutyCycle(duty_cycle)
    time.sleep(0.5)
    GPIO.output(SERVO_PIN, False)
    pwm.ChangeDutyCycle(0)

def main():
    recognizer = sr.Recognizer()

    try:
        # Configure API key
        genai.configure(api_key=credentials.api_key)

        # Define generation configuration for the model
        generation_config = {
            "temperature": 0.7,
            "top_p": 0.95,
            "top_k": 64,
            "max_output_tokens": 8192,
            "response_mime_type": "text/plain",
        }

        # Create and configure the model
        model = genai.GenerativeModel(
            model_name="gemini-1.5-flash",
            generation_config=generation_config,
        )

        # Start a chat session
        chat_session = model.start_chat(history=[])

        # Initialize pygame mixer
        pygame.mixer.init()

        print("Adjusting for ambient noise...")
        with sr.Microphone() as source:
            recognizer.adjust_for_ambient_noise(source)

        while True:
            try:
                with sr.Microphone() as source:
                    print("Listening...")
                    audio = recognizer.listen(source, timeout=5, phrase_time_limit=10)

                try:
                    # Recognize speech in Nepali
                    user_input = recognizer.recognize_google(audio, language="ne")
                    print(f"You said (in Nepali): {user_input}")

                    # Check for specific servo control commands in Nepali
                    if "मास्क खोल" in user_input:
                        print("Rotating servo to 180 degrees...")
                        rotate_servo(180)
                        continue
                    elif "मास्क बन्द" in user_input:
                        print("Rotating servo to 0 degrees...")
                        rotate_servo(0)
                        continue
                    elif "बन्द गर्नुहोस्" in user_input:
                        print("Shutting down...")
                        break

                    print("Generating answer using AI...")
                    response_length = 40
                    response = chat_session.send_message(user_input + f" कम शब्दहरुमा {response_length} भन्दा कम ")

                    cleaned_text = re.sub(r'[*]', '', response.text)
                    print(f"Answer generated by AI (in Nepali): {cleaned_text}")
                    answer = cleaned_text

                    # Generate TTS audio in Nepali
                    tts = gTTS(answer, lang="ne")
                    audio_file = "response.mp3"
                    tts.save(audio_file)

                    # Play the generated audio
                    pygame.mixer.music.load(audio_file)
                    pygame.mixer.music.play()
                    while pygame.mixer.music.get_busy():
                        pass
                    os.remove(audio_file)

                except sr.UnknownValueError:
                    print("Sorry, I could not understand the audio. Please try again.")
                except sr.RequestError as e:
                    print(f"Could not request results from Google Speech Recognition service; {e}")
                except sr.WaitTimeoutError:
                    print("Listening timed out. Please speak louder or clearer.")

            except sr.WaitTimeoutError:
                print("Timeout waiting for input, continuing to listen...")

            except KeyboardInterrupt:
                print("Exiting...")
                break

    except Exception as e:
        print(f"An error occurred: {e}")
    
    finally:
        pwm.stop()
        GPIO.cleanup()

if __name__ == "__main__":
    main()
